### ISSUE TITLE
10% of the EPSG values are the string "undefined"

### ISSUE THREAD

**Issue by vjohansen** [josueggh/proj4-list#1]
Of the 6137 entries in the object 703 is the string undefined

Example:

https://github.com/josueggh/proj4-list/blob/cee5e626027a85c2430bcbad85df1f7988ce27dc/src/list.js#L20024

```
  "EPSG:6319": [
  "EPSG:6319",
  "undefined"
],
  "EPSG:6272": [
  "EPSG:6272",
  "undefined"
],
  "EPSG:5756": [
  "EPSG:5756",
  "undefined"
],
```

A lot of them seem weird `"+vunits=m +no_defs +type=crs"` but some do not.

**Comment by josueggh** [comment]
Thanks for the catch. I remove the entried with "undefined" value.
